server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chuyun028/com-cx-manage/
          search-paths: config-dev
          username: chuyun028
          password: 898001885yu